name: Swift Transformers Formatting

on:
  workflow_call:

jobs:
  lint:
    name: Lint with swift-format
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install swift-format
      run: brew install swift-format
    - name: Run swift-format
      run: swift-format lint --recursive . --strict
